name: test

on:
  push:
    branches: [ "main" ]
    paths:
      - "demo/**"
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - run: demo/ci/build.bash
        working-directory: demo
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: demo/dist
          force_orphan: true
