name: demo-deoloy

on:
  push:
    branches: [ "main" ]
    paths:
      - "demo/**"
  pull_request:
    paths:
      - "demo/**"
  workflow_dispatch:

jobs:
  demo-deoloy:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: demo
    steps:
      - uses: actions/checkout@v3
      - run: ci/apt.bash
      - uses: swiftwasm/setup-swiftwasm@v1
        with:
          swift-version: "wasm-5.8.0-RELEASE"
      - run: ci/wabt.bash
      - run: ci/build.bash
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: demo/dist
          force_orphan: true
