name: demo-deoloy

on:
  push:
    branches: [ "main" ]
    paths:
      - "demo/**"
  pull_request:
  workflow_dispatch:

jobs:
  demo-deoloy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - run: demo/ci/apt.bash
      - uses: swiftwasm/setup-swiftwasm@v1
        with:
          swift-version: "wasm-5.7-SNAPSHOT-2023-01-09-a"
      - run: demo/ci/binaryen.bash
      - run: demo/ci/wabt.bash
      - run: demo/ci/build.bash
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: demo/dist
          force_orphan: true
