name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: vapor/swiftly-action@v0.2
        with:
          toolchain: "6.3"
      - run: swift test
