name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: "5.10"
      - uses: actions/checkout@v4
      - run: swift package resolve
      - run: swift build
      - run: swift test
